export type IdeaSkill = {
  id: string;
  title: string;
  purpose: string;
  whenToUse: string;
  questions: string[];
  outputContract: string[];
  suggestedTools: string[];
};

export const IDEA_SKILLS: IdeaSkill[] = [
  {
    id: "idea-flow-orchestrator",
    title: "Idea Flow Orchestrator",
    purpose: "Choose the right next skill and publishing action for an idea based on how much the user has provided.",
    whenToUse: "At the start of an agent session, after a user asks to create, improve, research, pivot, or promote an idea.",
    questions: [
      "Is this a raw sentence, answered intake, existing idea update, research request, critique request, validation request, prototype request, pivot request, or pro-candidate request?",
      "Does the agent need to ask more questions before publishing without inventing facts?",
      "Should this session create an idea, add a contribution, publish an owner-approved update, or stop on a blocker?",
      "Which skill should be applied next?",
    ],
    outputContract: [
      "Recommended next skill.",
      "Whether to ask questions, create a new idea, add a contribution, or publish an owner-approved update.",
      "Missing fields that block a coherent public page.",
      "A short tool plan using available FIS MCP tools.",
    ],
    suggestedTools: ["list_idea_skills", "get_idea_skill", "apply_idea_skill", "get_idea", "create_free_idea", "add_idea_contribution", "publish_idea_update"],
  },
  {
    id: "idea-interviewer",
    title: "Idea Interviewer",
    purpose: "Turn a vague idea into enough structured context to publish a useful first FreeIdeaStore page.",
    whenToUse: "Before create_free_idea, especially when the user has only a rough sentence or playful concept.",
    questions: [
      "Who is the first specific user or buyer?",
      "Where and when does the problem happen?",
      "What painful workaround exists today?",
      "What is the smallest useful version?",
      "What would make this idea worth testing this week?",
      "What is the biggest safety, legal, trust, or cost concern?",
      "Should the first public version feel playful, serious, technical, or investor-style?",
    ],
    outputContract: [
      "A short title (maximum 80 characters). Long titles break the page layout.",
      "One paragraph summary suitable for create_free_idea.summary.",
      "A short Current Signal section.",
      "A concrete Next Step that can be done cheaply.",
      "A named Risk that could kill or reshape the idea.",
      "A markdown body with Snapshot, User, Workflow, Risk, Next Step, and How To Help.",
    ],
    suggestedTools: ["create_free_idea", "add_idea_contribution"],
  },
  {
    id: "idea-document-architect",
    title: "Idea Document Architect",
    purpose: "Turn the user's first prompt or short interview answers into a coherent generic FreeIdeaStore public idea document.",
    whenToUse: "Before create_free_idea, after the agent has enough context to produce a useful first page without inventing facts.",
    questions: [
      "What is the clearest short title?",
      "What one-paragraph summary should appear on cards and listings?",
      "Who is the first user?",
      "What problem, workaround, or opportunity is visible?",
      "What is the smallest version worth testing?",
      "What is the current signal, main risk, and cheapest next step?",
      "How can strangers help with evidence, criticism, pivots, or prototype work?",
    ],
    outputContract: [
      "title: short, specific, and not hype-heavy. Maximum 80 characters — long titles break the page layout.",
      "summary: one paragraph for cards and listings.",
      "stage: usually raw, unless evidence already exists.",
      "category: one useful category tag.",
      "signal: one sentence describing why it deserves attention.",
      "next_step: one cheap action.",
      "risk: one visible risk.",
      "body: markdown using the universal 2-level spine when the idea has enough substance: Overview, People And Problem, Context And Evidence, Proposed Solution, Risks And Constraints, Validation, Prototype Or Pilot, Model And Distribution, Evolution.",
      "Named products, companies, services, datasets, regulators, and important public sources are clickable Markdown links on first meaningful mention when credible URLs are known.",
    ],
    suggestedTools: ["create_free_idea", "add_idea_contribution"],
  },
  {
    id: "idea-critic",
    title: "Idea Critic",
    purpose: "Pressure-test assumptions before time is wasted on a weak or unsafe idea.",
    whenToUse: "After an idea exists, before promoting it or publishing a more confident document.",
    questions: [
      "What assumption must be true for this to work?",
      "What law, platform rule, permit, license, or safety constraint may block it?",
      "What would make customers ignore it even if it works technically?",
      "What could make this more expensive than the value it creates?",
      "What is the strongest reason to trash it now?",
      "What narrower version avoids the biggest risk?",
    ],
    outputContract: [
      "Three strongest objections.",
      "One kill-signal test.",
      "One mitigation or narrower wedge.",
      "One contribution body suitable for kind=risk or kind=kill-signal.",
    ],
    suggestedTools: ["get_idea", "add_idea_contribution", "react_to_idea", "propose_idea_refinement"],
  },
  {
    id: "competitor-finder",
    title: "Competitor Finder",
    purpose: "Find existing products, services, substitutes, and manual workarounds before the idea is treated as novel.",
    whenToUse: "After an idea is drafted and before serious refinement, promotion, or prototype planning.",
    questions: [
      "What exact user job does this idea claim to solve?",
      "What would the user search for if they wanted this today?",
      "Which direct competitors already sell the same promise?",
      "Which indirect substitutes solve the problem differently?",
      "Which local/manual/offline workaround is most common?",
      "What competitor weakness creates a possible wedge?",
      "Which sources prove each competitor exists?",
    ],
    outputContract: [
      "Direct competitor list where each named product or company is a Markdown link to its official page when a credible URL exists.",
      "Indirect substitute/workaround list with source URLs when available.",
      "Comparison notes: customer, pricing/model, channel, geography, and key weakness.",
      "One evidence contribution body summarizing what already exists.",
      "One refinement or pivot recommendation if the idea is not differentiated.",
    ],
    suggestedTools: ["get_idea", "add_idea_contribution", "propose_idea_refinement"],
  },
  {
    id: "idea-researcher",
    title: "Idea Researcher",
    purpose: "Convert public evidence and source-backed observations into useful idea history.",
    whenToUse: "When the idea needs facts, market signals, competitor notes, regulation notes, or validation evidence.",
    questions: [
      "Which claim needs evidence most?",
      "Which sources are public and acceptable to cite?",
      "Who else solves this today?",
      "What user behavior or market signal suggests demand?",
      "What regulation, safety, or operational source must be checked?",
      "What remains unknown after this pass?",
    ],
    outputContract: [
      "Source-backed evidence notes with clickable Markdown links when available.",
      "Competitor/current-workaround notes where each named product or service is linked to its official page when a credible URL exists.",
      "Open questions that still block confidence.",
      "Contribution bodies suitable for kind=evidence or kind=risk.",
    ],
    suggestedTools: ["get_idea", "add_idea_contribution", "propose_idea_refinement"],
  },
  {
    id: "idea-refiner",
    title: "Idea Refiner",
    purpose: "Merge useful history into a clearer canonical public idea document without losing important caveats.",
    whenToUse: "After enough notes, critiques, or answers exist to improve the public page.",
    questions: [
      "What should the public reader understand in the first 20 seconds?",
      "Which evidence has earned a place in the canonical document?",
      "Which risks must stay visible, not hidden?",
      "What should be moved to contribution history instead of the main document?",
      "What is the next validation step after this update?",
    ],
    outputContract: [
      "Complete replacement markdown document.",
      "Updated summary, stage, category, signal, next_step, and risk fields when appropriate.",
      "Preserve useful existing content unless it is outdated or misleading.",
      "Shape serious canonical documents into the universal 2-level spine: Overview, People And Problem, Context And Evidence, Proposed Solution, Risks And Constraints, Validation, Prototype Or Pilot, Model And Distribution, Evolution.",
      "Convert named products, companies, services, datasets, regulators, and important public sources into clickable Markdown links on first meaningful mention when credible URLs exist.",
      "Use publish_idea_update only when the authenticated owner is ready.",
    ],
    suggestedTools: ["get_idea", "publish_idea_update", "add_idea_contribution"],
  },
  {
    id: "pivot-generator",
    title: "Pivot Generator",
    purpose: "Find sharper customer, market, wedge, or format alternatives when the original idea is too broad or risky.",
    whenToUse: "When critique finds a blocker but the underlying insight may still be valuable.",
    questions: [
      "Which part of the idea is valuable even if the first version fails?",
      "Who has the same pain with less regulation or lower operational risk?",
      "Can this become content, tooling, infrastructure, marketplace, service, or data product instead?",
      "What smaller geography, event, niche, or workflow makes testing easier?",
      "Which pivot should be tested first and why?",
    ],
    outputContract: [
      "Three pivot options.",
      "One recommended narrow wedge.",
      "Risk reduction explanation.",
      "Contribution body suitable for kind=pivot.",
    ],
    suggestedTools: ["get_idea", "add_idea_contribution", "react_to_idea", "propose_idea_refinement"],
  },
  {
    id: "validation-planner",
    title: "Validation Planner",
    purpose: "Turn an idea into a cheap validation plan that can prove, narrow, pivot, or trash it quickly.",
    whenToUse: "After an idea has a clear first user, problem, risk, and smallest version.",
    questions: [
      "What is the riskiest assumption?",
      "What behavior would prove real interest?",
      "What is the cheapest test that can run this week?",
      "Who can be contacted or observed without building the full product?",
      "What result means continue?",
      "What result means pivot, park, or trash?",
    ],
    outputContract: [
      "Riskiest assumption.",
      "Test design with target users, method, cost, and timebox.",
      "Pass, weak-pass, and fail thresholds.",
      "Data to collect.",
      "One contribution body suitable for kind=evidence or kind=kill-signal.",
      "Updated next step if the owner approves a canonical refinement.",
    ],
    suggestedTools: ["get_idea", "add_idea_contribution", "propose_idea_refinement", "publish_idea_update"],
  },
  {
    id: "prototype-planner",
    title: "Prototype Planner",
    purpose: "Define the smallest prototype that can test the idea's core workflow without pretending the full product exists.",
    whenToUse: "After validation has identified the key behavior to test or when a user asks how to build the first demo.",
    questions: [
      "What single workflow must the prototype prove?",
      "What can be faked manually behind the scenes?",
      "What must be real for the test to be honest?",
      "What data, permissions, integrations, or assets are required?",
      "What safety, privacy, legal, or trust constraints affect the prototype?",
      "What should be deliberately excluded from version one?",
    ],
    outputContract: [
      "Prototype goal.",
      "Core user flow.",
      "In-scope and out-of-scope list.",
      "Manual/fakeable parts.",
      "Required data, services, or permissions.",
      "Demo script and success criteria.",
      "One contribution body suitable for kind=prototype.",
    ],
    suggestedTools: ["get_idea", "add_idea_contribution", "propose_idea_refinement"],
  },
  {
    id: "pro-candidate-assessor",
    title: "Pro Candidate Assessor",
    purpose: "Decide whether an idea deserves ProIdeaStore diligence or should stay in FreeIdeaStore.",
    whenToUse: "After research, critique, and refinement create enough evidence for serious review.",
    questions: [
      "Is there a specific buyer or sponsor?",
      "Is the painful problem frequent enough?",
      "Is there evidence beyond personal enthusiasm?",
      "Are the legal, safety, financial, or trust risks named?",
      "Is there a prototype or credible prototype plan?",
      "Can a pitch deck or diligence packet be produced without inventing facts?",
    ],
    outputContract: [
      "Score 0-5 for customer clarity, evidence, risk clarity, buildability, and commercial potential.",
      "Decision: stay free, refine more, pivot, trash, or promote.",
      "Missing diligence list.",
      "If ready, call promote_to_pro_candidate.",
    ],
    suggestedTools: ["get_idea", "add_idea_contribution", "promote_to_pro_candidate", "dry_run_dynamic_idea_book"],
  },
];
