import { brandCss } from './brand';
import { MARKDOWN_CSS } from './markdown';
import { readerSettingsCss } from './reader-settings';
import { navCss } from './site-nav';

export function ideaHomeStyles(): string {
  return `<style>
*{box-sizing:border-box;margin:0;padding:0}
:root{--page:#f8fafc;--panel:#fff;--panel-alt:#fbfdfe;--topbar-bg:rgba(255,255,255,.95);--ink:#111827;--muted:#334155;--line:#cbd5e1;--accent:#0e7490;--accent-strong:#0f4c5c;--mark:#ecfeff;--bad:#dc2626;--body-text:#273646;--title-text:#263445;--strong-text:#17202a;--chapter-badge:#e2f3f7;--focus:#cffafe;--hover-line:#67c1d4;--shadow:0 16px 36px rgba(15,23,42,.06)}
body{background:var(--page);color:var(--ink);font-family:Manrope,system-ui,sans-serif;line-height:1.68}
a{color:inherit;text-decoration:none}
.book-topbar{position:sticky;top:0;z-index:20;display:flex;align-items:center;gap:.8rem;border-bottom:1px solid var(--line);background:var(--topbar-bg);padding:.5rem .95rem;backdrop-filter:blur(14px)}
.top-brand{display:flex;align-items:center;gap:.65rem;min-width:0;font-weight:900;margin-right:auto}.top-brand strong{display:block;max-width:min(60vw,540px);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
${brandCss()}
.topbar-nav{display:flex;align-items:center;gap:.15rem}.topbar-nav a{padding:.4rem .6rem;border-radius:6px;color:var(--muted);font-size:.78rem;font-weight:700}.topbar-nav a:hover{background:var(--mark);color:var(--accent-strong)}.book-shell{display:grid;grid-template-columns:292px minmax(0,1fr) 300px;min-height:calc(100vh - 62px)}
.book-sidebar{position:sticky;top:62px;height:calc(100vh - 62px);overflow:auto;border-right:1px solid var(--line);background:var(--panel);padding:1rem}
.book-search{position:relative;margin:.75rem 0}.book-search input{width:100%;border:1px solid var(--line);border-radius:8px;background:var(--panel-alt);color:var(--ink);font:inherit;font-size:.8rem;padding:.58rem .65rem}.book-search input:focus{border-color:var(--hover-line);outline:2px solid var(--focus)}
.nav-title{display:flex;justify-content:space-between;gap:.75rem;color:var(--title-text);font-size:.68rem;text-transform:uppercase;font-weight:900;letter-spacing:.12em;margin:.7rem 0 .42rem}.chapter-list{display:grid;gap:.28rem}.chapter-link{display:grid;grid-template-columns:28px minmax(0,1fr);gap:.55rem;align-items:center;border:1px solid transparent;border-radius:8px;padding:.54rem .56rem;color:var(--strong-text)}.chapter-link:hover{background:var(--mark);border-color:var(--hover-line)}.chapter-link b{display:grid;width:26px;height:26px;place-items:center;border-radius:999px;background:var(--chapter-badge);color:var(--accent-strong);font-size:.7rem}.chapter-link span{display:block;font-size:.82rem;font-weight:900;line-height:1.25}
.mobile-book-nav{display:none;border-bottom:1px solid var(--line);background:var(--panel);padding:.75rem 1rem}.mobile-book-nav summary{cursor:pointer;color:var(--accent-strong);font-weight:900}.mobile-book-nav .chapter-list{margin-top:.65rem;grid-template-columns:repeat(auto-fit,minmax(210px,1fr))}
.content-wrap{display:grid;grid-template-columns:minmax(0,920px);justify-content:center;padding:2.2rem 1.35rem 4rem}.article{width:100%}.crumb{display:flex;flex-wrap:wrap;gap:.45rem;align-items:center;color:var(--accent-strong);font-size:.73rem;font-weight:900;text-transform:uppercase;letter-spacing:.09em;margin-bottom:.78rem}
h1{font-family:Fraunces,serif;font-size:clamp(1.6rem,3.5vw,2.8rem);line-height:1.08;letter-spacing:-.01em;margin-bottom:1rem;max-width:880px}h2{font-family:Fraunces,serif;font-size:1.7rem;margin:1.55rem 0 .55rem;scroll-margin-top:1rem}h3{font-size:1.08rem;margin:1.35rem 0 .35rem;scroll-margin-top:1rem}
p{color:var(--body-text);margin:.78rem 0;max-width:760px}ul,ol{display:grid;gap:.42rem;margin:.78rem 0 1rem 1.25rem;color:var(--body-text);max-width:760px}li::marker{color:var(--accent-strong);font-weight:900}
.summary{border:1px solid var(--line);border-left:4px solid var(--accent);background:var(--panel);padding:1rem 1.05rem;border-radius:8px;color:var(--body-text);font-weight:800;box-shadow:var(--shadow);margin-bottom:1rem;max-width:820px}.meta{display:flex;flex-wrap:wrap;gap:.45rem;margin-bottom:1.25rem}.pill{border:1px solid var(--line);border-radius:999px;background:var(--panel);padding:.32rem .62rem;color:var(--title-text);font-size:.7rem;font-weight:900;text-transform:uppercase}
.idea-diagram{background:var(--panel);border:1px solid var(--line);border-radius:12px;box-shadow:var(--shadow);padding:1.25rem;margin-bottom:1.25rem;max-width:820px;overflow-x:auto}.idea-diagram svg{display:block;max-width:100%;height:auto;margin:0 auto}.idea-diagram-label{color:var(--muted);font-size:.72rem;font-weight:900;text-transform:uppercase;letter-spacing:.08em;margin-bottom:.65rem}
.sources{background:var(--panel);border:1px solid var(--line);border-radius:8px;box-shadow:var(--shadow);padding:1.1rem 1.15rem;margin-top:1rem;scroll-margin-top:74px}.sources h2{font-size:1.1rem;margin:0 0 .3rem}.sources-intro{color:var(--muted);font-size:.85rem;margin:0 0 .8rem}.source-list{display:grid;gap:.4rem;margin:0;padding:0;list-style:none;max-width:none}.source-row{display:flex;flex-wrap:wrap;gap:.5rem;align-items:baseline;border-left:3px solid var(--line);padding-left:.6rem;font-size:.84rem}.source-url{color:var(--accent-strong);font-weight:900;overflow-wrap:anywhere}.source-where{color:var(--muted);font-size:.78rem}.source-where a{color:var(--accent-strong)}.source-citations{color:var(--muted);font-size:.72rem;font-weight:900;text-transform:uppercase;letter-spacing:.05em}.source-dead{border:1px solid var(--bad);border-radius:999px;color:var(--bad);font-size:.62rem;font-weight:900;padding:.08rem .4rem;text-transform:uppercase}
.chapter-body,.comments,.research{background:var(--panel);border:1px solid var(--line);border-radius:8px;box-shadow:var(--shadow);padding:1.1rem 1.15rem}.chapter-body>*:first-child{margin-top:0}
.research{margin-top:1rem;scroll-margin-top:74px}.research h2{font-size:1.1rem;margin:0 0 .3rem}.research-intro{color:var(--muted);font-size:.85rem;margin:0 0 .9rem}.research-group{margin-top:1.15rem}.research-group:first-of-type{margin-top:0}.research-group h3{display:flex;align-items:center;gap:.45rem;font-size:.74rem;font-weight:900;text-transform:uppercase;letter-spacing:.09em;color:var(--strong-text);margin:0 0 .2rem}.research-count{border:1px solid var(--line);border-radius:999px;background:var(--mark);color:var(--accent-strong);font-size:.68rem;padding:.06rem .42rem}.research-blurb{color:var(--muted);font-size:.78rem;margin:0 0 .5rem}
.research-item{border:1px solid var(--line);border-radius:8px;background:var(--panel-alt);margin-bottom:.45rem;scroll-margin-top:74px}.research-item[open]{border-color:var(--hover-line)}.research-item summary{display:flex;flex-wrap:wrap;gap:.45rem;align-items:baseline;cursor:pointer;padding:.6rem .7rem;list-style:none}.research-item summary::-webkit-details-marker{display:none}.research-item summary:hover{background:var(--mark)}.research-item summary:focus-visible{outline:2px solid var(--focus)}
.research-kind{flex:0 0 auto;border:1px solid var(--line);border-radius:999px;background:var(--panel);color:var(--accent-strong);font-size:.62rem;font-weight:900;letter-spacing:.05em;padding:.12rem .42rem;text-transform:uppercase}.research-excerpt{flex:1 1 240px;min-width:0;color:var(--strong-text);font-size:.84rem;font-weight:700;line-height:1.4}
.research-byline{color:var(--muted);font-size:.74rem;margin:0;padding:0 .7rem}.research-byline a{color:var(--accent-strong);font-weight:900}.research-byline time{margin-left:.35rem}.research-body{color:var(--body-text);font-size:.86rem;line-height:1.6;margin:.4rem 0 0;padding:0 .7rem .75rem;max-width:none;white-space:pre-wrap;overflow-wrap:anywhere}
.toc-rail{position:sticky;top:62px;height:calc(100vh - 62px);overflow:auto;border-left:1px solid var(--line);background:var(--panel-alt);padding:1.1rem .95rem}.toc-title{color:var(--title-text);font-size:.68rem;font-weight:900;letter-spacing:.12em;text-transform:uppercase;margin-bottom:.35rem}.signal-box{display:grid;gap:.75rem}.signal-box>div{border-left:3px solid var(--line);padding-left:.65rem}.signal-box strong{display:block;color:var(--strong-text);font-size:.72rem;text-transform:uppercase}.signal-box span,.signal-box p{display:block;color:var(--muted);font-size:.82rem;margin:0}.toc-box{display:grid;gap:.32rem;margin-top:.32rem}.toc-box a{display:block;border-left:2px solid transparent;color:var(--title-text);font-size:.78rem;font-weight:900;line-height:1.35;padding:.28rem 0 .28rem .55rem}.toc-box a:hover{border-left-color:var(--accent);color:var(--accent-strong);background:var(--mark)}
.actions,.reaction-buttons{display:flex;gap:.5rem;flex-wrap:wrap}.button,.react-button{border:1px solid var(--accent);border-radius:8px;background:var(--accent);color:#fff;cursor:pointer;padding:.58rem .75rem;font-size:.78rem;font-weight:900}.button.secondary,.react-button{background:var(--panel);color:var(--accent-strong)}.react-button:disabled{cursor:not-allowed;opacity:.58}.reaction-status{color:var(--muted);font-size:.76rem;margin-top:.35rem}
.comments{margin-top:1rem}.comments h2{font-size:1.1rem;margin-bottom:.3rem}.comment-form{display:grid;gap:.6rem;border-top:1px solid var(--line);margin-top:.9rem;padding-top:.9rem}.comment-form label{display:grid;gap:.28rem;color:var(--muted);font-size:.74rem;font-weight:900;text-transform:uppercase}.comment-form textarea{width:100%;border:1px solid var(--line);border-radius:8px;background:var(--panel-alt);color:var(--ink);padding:.65rem;font:inherit;min-height:96px;resize:vertical}.comment-list{display:grid;gap:.65rem;margin-top:.9rem}.comment{border:1px solid var(--line);border-radius:8px;background:var(--panel-alt);padding:.75rem}.comment-head{display:flex;flex-wrap:wrap;gap:.4rem;align-items:center;color:var(--muted);font-size:.76rem}.comment-head strong{color:var(--ink)}.comment-kind{border:1px solid var(--line);border-radius:999px;background:var(--mark);color:var(--accent-strong);font-size:.65rem;font-weight:900;padding:.12rem .4rem;text-transform:uppercase}.comment p{color:var(--muted);font-size:.9rem;margin-top:.35rem;white-space:pre-wrap}.comment-status{color:var(--muted);font-size:.82rem;margin-top:.55rem}.comment-status.err{color:var(--bad)}.comment-empty,.auth-callout{border:1px dashed var(--line);border-radius:8px;color:var(--muted);padding:.8rem;font-size:.86rem}.auth-callout{display:none;margin-top:.8rem;background:var(--panel-alt)}.auth-callout a{color:var(--accent-strong);font-weight:900}
@media(max-width:1180px){.book-shell{grid-template-columns:280px minmax(0,1fr)}.toc-rail{display:none}}
@media(max-width:860px){.top-brand strong{max-width:min(55vw,280px)}.book-shell{display:block;min-height:0}.book-sidebar{display:none}.mobile-book-nav{display:block}.content-wrap{padding:1.3rem 1rem 3rem}.sources{background:var(--panel);border:1px solid var(--line);border-radius:8px;box-shadow:var(--shadow);padding:1.1rem 1.15rem;margin-top:1rem;scroll-margin-top:74px}.sources h2{font-size:1.1rem;margin:0 0 .3rem}.sources-intro{color:var(--muted);font-size:.85rem;margin:0 0 .8rem}.source-list{display:grid;gap:.4rem;margin:0;padding:0;list-style:none;max-width:none}.source-row{display:flex;flex-wrap:wrap;gap:.5rem;align-items:baseline;border-left:3px solid var(--line);padding-left:.6rem;font-size:.84rem}.source-url{color:var(--accent-strong);font-weight:900;overflow-wrap:anywhere}.source-where{color:var(--muted);font-size:.78rem}.source-where a{color:var(--accent-strong)}.source-citations{color:var(--muted);font-size:.72rem;font-weight:900;text-transform:uppercase;letter-spacing:.05em}.source-dead{border:1px solid var(--bad);border-radius:999px;color:var(--bad);font-size:.62rem;font-weight:900;padding:.08rem .4rem;text-transform:uppercase}
.chapter-body,.comments,.research{padding:.9rem}h1{font-size:clamp(1.4rem,5vw,2.2rem)}}
${navCss(860)}
${MARKDOWN_CSS}
/* Typed research entries: provenance and confidence must be visible at a glance,
   because an inferred claim must not read like a confirmed one. */
.research-tag{flex:0 0 auto;border:1px solid var(--line);border-radius:999px;background:var(--panel-alt);color:var(--muted);font-size:.6rem;font-weight:900;letter-spacing:.04em;padding:.12rem .42rem;text-transform:uppercase;margin-left:.3rem}
.research-tag.prov-confirmed,.research-tag.prov-extracted{border-color:#0f766e;background:#ecfdf5;color:#0f766e}
.research-tag.prov-derived{border-color:var(--accent);background:var(--mark);color:var(--accent-strong)}
.research-tag.prov-inferred,.research-tag.prov-human-asserted{border-color:#b45309;background:#fffbeb;color:#92400e}
.research-tag.conf-low{border-color:#b91c1c;background:#fef2f2;color:#b91c1c}
.research-pager{display:flex;flex-wrap:wrap;gap:.75rem;align-items:baseline;border-top:1px solid var(--line);margin-top:1rem;padding-top:.75rem;font-size:.8rem;font-weight:900}.research-pager a{color:var(--accent-strong)}.research-pager span{color:var(--muted)}.research-pager-at{font-weight:700}
.research-tag.pending{border-color:#b45309;background:#fffbeb;color:#92400e}
.research-tag.resolved{border-color:#0f766e;background:#ecfdf5;color:#0f766e}
[data-theme="dark"] .research-pager{display:flex;flex-wrap:wrap;gap:.75rem;align-items:baseline;border-top:1px solid var(--line);margin-top:1rem;padding-top:.75rem;font-size:.8rem;font-weight:900}.research-pager a{color:var(--accent-strong)}.research-pager span{color:var(--muted)}.research-pager-at{font-weight:700}
.research-tag.pending{background:#3a2a05;color:#fcd34d}
[data-theme="dark"] .research-tag.resolved{background:#052e2b;color:#6ee7b7}
.research-tag.superseded{border-color:var(--muted);background:var(--panel);color:var(--muted);text-decoration:line-through}
.research-item.is-superseded>summary .research-excerpt{color:var(--muted);text-decoration:line-through;text-decoration-thickness:1px}
.research-superseded{color:var(--muted);font-size:.78rem;margin:.2rem 0 0;padding:0 .7rem}.research-superseded a{color:var(--accent-strong);font-weight:900}
.research-source{margin-left:.45rem;color:var(--accent-strong);font-weight:900}
.research-accessed{margin-left:.35rem;color:var(--muted)}
[data-theme="dark"] .research-tag.prov-confirmed,[data-theme="dark"] .research-tag.prov-extracted{background:#052e2b;color:#6ee7b7}
[data-theme="dark"] .research-tag.prov-inferred,[data-theme="dark"] .research-tag.prov-human-asserted{background:#3a2a05;color:#fcd34d}
[data-theme="dark"] .research-tag.conf-low{background:#3f1414;color:#fca5a5}
/* Short ideas render without the chapter sidebar — close the column it left. */
.book-shell.single-page{grid-template-columns:minmax(0,1fr) 300px}
@media(max-width:1180px){.book-shell.single-page{grid-template-columns:minmax(0,1fr)}}
${readerSettingsCss()}
</style>`;
}
